// Autogenerated from Pigeon (v15.0.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package dev.hasali.zenith.cast_framework.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class RoutesScanningMode(val raw: Int) {
  NONE(0),
  PASSIVE(1),
  ACTIVE(2);

  companion object {
    fun ofRaw(raw: Int): RoutesScanningMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class MediaQueueType(val raw: Int) {
  GENERIC(0),
  TVSERIES(1),
  VIDEOPLAYLIST(2),
  MOVIE(3);

  companion object {
    fun ofRaw(raw: Int): MediaQueueType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class MediaTrackType(val raw: Int) {
  TEXT(0);

  companion object {
    fun ofRaw(raw: Int): MediaTrackType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class MediaTrackSubtype(val raw: Int) {
  SUBTITLES(0);

  companion object {
    fun ofRaw(raw: Int): MediaTrackSubtype? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class MediaType(val raw: Int) {
  MOVIE(0),
  TVSHOW(1),
  UNKNOWN(2);

  companion object {
    fun ofRaw(raw: Int): MediaType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ResumeState(val raw: Int) {
  PAUSE(0),
  PLAY(1),
  UNCHANGED(2);

  companion object {
    fun ofRaw(raw: Int): ResumeState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PlayerState(val raw: Int) {
  IDLE(0),
  BUFFERING(1),
  LOADING(2),
  PAUSED(3),
  PLAYING(4),
  UNKNOWN(5);

  companion object {
    fun ofRaw(raw: Int): PlayerState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaRoute (
  val id: String,
  val name: String,
  val description: String? = null,
  val isSelected: Boolean

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): MediaRoute {
      val id = list[0] as String
      val name = list[1] as String
      val description = list[2] as String?
      val isSelected = list[3] as Boolean
      return MediaRoute(id, name, description, isSelected)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      id,
      name,
      description,
      isSelected,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaLoadRequestData (
  val mediaInfo: MediaInfo? = null,
  val queueData: MediaQueueData? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): MediaLoadRequestData {
      val mediaInfo: MediaInfo? = (list[0] as List<Any?>?)?.let {
        MediaInfo.fromList(it)
      }
      val queueData: MediaQueueData? = (list[1] as List<Any?>?)?.let {
        MediaQueueData.fromList(it)
      }
      return MediaLoadRequestData(mediaInfo, queueData)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      mediaInfo?.toList(),
      queueData?.toList(),
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaInfo (
  val url: String? = null,
  val mediaTracks: List<MediaTrack?>? = null,
  val metadata: MediaMetadata? = null,
  val streamDuration: Long? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): MediaInfo {
      val url = list[0] as String?
      val mediaTracks = list[1] as List<MediaTrack?>?
      val metadata: MediaMetadata? = (list[2] as List<Any?>?)?.let {
        MediaMetadata.fromList(it)
      }
      val streamDuration = list[3].let { if (it is Int) it.toLong() else it as Long? }
      return MediaInfo(url, mediaTracks, metadata, streamDuration)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      url,
      mediaTracks,
      metadata?.toList(),
      streamDuration,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaQueueData (
  val items: List<MediaQueueItem?>? = null,
  val startIndex: Long? = null,
  val queueType: MediaQueueType? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): MediaQueueData {
      val items = list[0] as List<MediaQueueItem?>?
      val startIndex = list[1].let { if (it is Int) it.toLong() else it as Long? }
      val queueType: MediaQueueType? = (list[2] as Int?)?.let {
        MediaQueueType.ofRaw(it)
      }
      return MediaQueueData(items, startIndex, queueType)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      items,
      startIndex,
      queueType?.raw,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaQueueItem (
  val mediaInfo: MediaInfo? = null,
  val activeTrackIds: List<Long?>? = null,
  val autoPlay: Boolean? = null,
  val startTime: Double? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): MediaQueueItem {
      val mediaInfo: MediaInfo? = (list[0] as List<Any?>?)?.let {
        MediaInfo.fromList(it)
      }
      val activeTrackIds = list[1] as List<Long?>?
      val autoPlay = list[2] as Boolean?
      val startTime = list[3] as Double?
      return MediaQueueItem(mediaInfo, activeTrackIds, autoPlay, startTime)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      mediaInfo?.toList(),
      activeTrackIds,
      autoPlay,
      startTime,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaTrack (
  val trackId: Long,
  val type: MediaTrackType,
  val contentId: String,
  val subtype: MediaTrackSubtype? = null,
  val name: String? = null,
  val language: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): MediaTrack {
      val trackId = list[0].let { if (it is Int) it.toLong() else it as Long }
      val type = MediaTrackType.ofRaw(list[1] as Int)!!
      val contentId = list[2] as String
      val subtype: MediaTrackSubtype? = (list[3] as Int?)?.let {
        MediaTrackSubtype.ofRaw(it)
      }
      val name = list[4] as String?
      val language = list[5] as String?
      return MediaTrack(trackId, type, contentId, subtype, name, language)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      trackId,
      type.raw,
      contentId,
      subtype?.raw,
      name,
      language,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaMetadata (
  val mediaType: MediaType,
  val title: String? = null,
  val seriesTitle: String? = null,
  val seasonNumber: Long? = null,
  val episodeNumber: Long? = null,
  val poster: MediaMetadataImage? = null,
  val backdrop: MediaMetadataImage? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): MediaMetadata {
      val mediaType = MediaType.ofRaw(list[0] as Int)!!
      val title = list[1] as String?
      val seriesTitle = list[2] as String?
      val seasonNumber = list[3].let { if (it is Int) it.toLong() else it as Long? }
      val episodeNumber = list[4].let { if (it is Int) it.toLong() else it as Long? }
      val poster: MediaMetadataImage? = (list[5] as List<Any?>?)?.let {
        MediaMetadataImage.fromList(it)
      }
      val backdrop: MediaMetadataImage? = (list[6] as List<Any?>?)?.let {
        MediaMetadataImage.fromList(it)
      }
      return MediaMetadata(mediaType, title, seriesTitle, seasonNumber, episodeNumber, poster, backdrop)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      mediaType.raw,
      title,
      seriesTitle,
      seasonNumber,
      episodeNumber,
      poster?.toList(),
      backdrop?.toList(),
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaMetadataImage (
  val url: String,
  val width: Long,
  val height: Long

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): MediaMetadataImage {
      val url = list[0] as String
      val width = list[1].let { if (it is Int) it.toLong() else it as Long }
      val height = list[2].let { if (it is Int) it.toLong() else it as Long }
      return MediaMetadataImage(url, width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      url,
      width,
      height,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaSeekOptions (
  val position: Long,
  val resumeState: ResumeState

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): MediaSeekOptions {
      val position = list[0].let { if (it is Int) it.toLong() else it as Long }
      val resumeState = ResumeState.ofRaw(list[1] as Int)!!
      return MediaSeekOptions(position, resumeState)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      position,
      resumeState.raw,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaStatus (
  val playerState: PlayerState,
  val mediaInfo: MediaInfo? = null,
  val streamPosition: Long,
  val playbackRate: Double,
  val currentItemIndex: Long? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): MediaStatus {
      val playerState = PlayerState.ofRaw(list[0] as Int)!!
      val mediaInfo: MediaInfo? = (list[1] as List<Any?>?)?.let {
        MediaInfo.fromList(it)
      }
      val streamPosition = list[2].let { if (it is Int) it.toLong() else it as Long }
      val playbackRate = list[3] as Double
      val currentItemIndex = list[4].let { if (it is Int) it.toLong() else it as Long? }
      return MediaStatus(playerState, mediaInfo, streamPosition, playbackRate, currentItemIndex)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      playerState.raw,
      mediaInfo?.toList(),
      streamPosition,
      playbackRate,
      currentItemIndex,
    )
  }
}
@Suppress("UNCHECKED_CAST")
private object CastApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaInfo.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaLoadRequestData.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaMetadata.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaMetadataImage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaQueueData.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaQueueItem.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaSeekOptions.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaTrack.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is MediaInfo -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is MediaLoadRequestData -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is MediaMetadata -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is MediaMetadataImage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is MediaQueueData -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is MediaQueueItem -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is MediaSeekOptions -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is MediaTrack -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CastApi {
  fun init(receiverAppId: String)
  fun registerRoutesListener(mode: RoutesScanningMode)
  fun unregisterRoutesListener(mode: RoutesScanningMode)
  fun selectRoute(id: String?)
  fun load(loadRequestData: MediaLoadRequestData)
  fun setActiveMediaTracks(trackIds: List<Long>)
  fun play()
  fun pause()
  fun seek(options: MediaSeekOptions)
  fun queueNext()
  fun queuePrev()
  fun setPlaybackRate(playbackRate: Double)
  fun stop()

  companion object {
    /** The codec used by CastApi. */
    val codec: MessageCodec<Any?> by lazy {
      CastApiCodec
    }
    /** Sets up an instance of `CastApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: CastApi?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.init", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val receiverAppIdArg = args[0] as String
            var wrapped: List<Any?>
            try {
              api.init(receiverAppIdArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.registerRoutesListener", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modeArg = RoutesScanningMode.ofRaw(args[0] as Int)!!
            var wrapped: List<Any?>
            try {
              api.registerRoutesListener(modeArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.unregisterRoutesListener", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modeArg = RoutesScanningMode.ofRaw(args[0] as Int)!!
            var wrapped: List<Any?>
            try {
              api.unregisterRoutesListener(modeArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.selectRoute", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String?
            var wrapped: List<Any?>
            try {
              api.selectRoute(idArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.load", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val loadRequestDataArg = args[0] as MediaLoadRequestData
            var wrapped: List<Any?>
            try {
              api.load(loadRequestDataArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.setActiveMediaTracks", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val trackIdsArg = args[0] as List<Long>
            var wrapped: List<Any?>
            try {
              api.setActiveMediaTracks(trackIdsArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.play", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              api.play()
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.pause", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              api.pause()
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.seek", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsArg = args[0] as MediaSeekOptions
            var wrapped: List<Any?>
            try {
              api.seek(optionsArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.queueNext", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              api.queueNext()
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.queuePrev", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              api.queuePrev()
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.setPlaybackRate", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playbackRateArg = args[0] as Double
            var wrapped: List<Any?>
            try {
              api.setPlaybackRate(playbackRateArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.stop", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              api.stop()
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
@Suppress("UNCHECKED_CAST")
private object CastEventsApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaInfo.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaMetadata.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaMetadataImage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaRoute.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaStatus.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaTrack.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is MediaInfo -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is MediaMetadata -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is MediaMetadataImage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is MediaRoute -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is MediaStatus -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is MediaTrack -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
@Suppress("UNCHECKED_CAST")
class CastEventsApi(private val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by CastEventsApi. */
    val codec: MessageCodec<Any?> by lazy {
      CastEventsApiCodec
    }
  }
  fun onRoutesChanged(routesArg: List<MediaRoute>, callback: (Result<Unit>) -> Unit) {
    val channelName = "dev.flutter.pigeon.cast_framework.CastEventsApi.onRoutesChanged"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(routesArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onStatusUpdated(statusArg: MediaStatus?, callback: (Result<Unit>) -> Unit) {
    val channelName = "dev.flutter.pigeon.cast_framework.CastEventsApi.onStatusUpdated"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(statusArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
