// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.hasali.zenith.cast_framework.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class RoutesScanningMode(val raw: Int) {
  NONE(0),
  PASSIVE(1),
  ACTIVE(2);

  companion object {
    fun ofRaw(raw: Int): RoutesScanningMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class MediaQueueType(val raw: Int) {
  GENERIC(0),
  TV_SERIES(1),
  VIDEO_PLAYLIST(2),
  MOVIE(3);

  companion object {
    fun ofRaw(raw: Int): MediaQueueType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class MediaTrackType(val raw: Int) {
  VIDEO(0),
  AUDIO(1),
  TEXT(2);

  companion object {
    fun ofRaw(raw: Int): MediaTrackType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class MediaTrackSubtype(val raw: Int) {
  SUBTITLES(0);

  companion object {
    fun ofRaw(raw: Int): MediaTrackSubtype? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class MediaType(val raw: Int) {
  MOVIE(0),
  TV_SHOW(1),
  UNKNOWN(2);

  companion object {
    fun ofRaw(raw: Int): MediaType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ResumeState(val raw: Int) {
  PAUSE(0),
  PLAY(1),
  UNCHANGED(2);

  companion object {
    fun ofRaw(raw: Int): ResumeState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class IdleReason(val raw: Int) {
  CANCELED(0),
  ERROR(1),
  FINISHED(2),
  INTERRUPTED(3),
  NONE(4);

  companion object {
    fun ofRaw(raw: Int): IdleReason? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PlayerState(val raw: Int) {
  IDLE(0),
  BUFFERING(1),
  LOADING(2),
  PAUSED(3),
  PLAYING(4),
  UNKNOWN(5);

  companion object {
    fun ofRaw(raw: Int): PlayerState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaRoute (
  val id: String,
  val name: String,
  val description: String? = null,
  val isSelected: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaRoute {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val description = pigeonVar_list[2] as String?
      val isSelected = pigeonVar_list[3] as Boolean
      return MediaRoute(id, name, description, isSelected)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      description,
      isSelected,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaLoadRequestData (
  val mediaInfo: MediaInfo? = null,
  val queueData: MediaQueueData? = null,
  val customDataJson: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaLoadRequestData {
      val mediaInfo = pigeonVar_list[0] as MediaInfo?
      val queueData = pigeonVar_list[1] as MediaQueueData?
      val customDataJson = pigeonVar_list[2] as String?
      return MediaLoadRequestData(mediaInfo, queueData, customDataJson)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      mediaInfo,
      queueData,
      customDataJson,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaInfo (
  val url: String? = null,
  val mediaTracks: List<MediaTrack>? = null,
  val metadata: MediaMetadata? = null,
  val streamDuration: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaInfo {
      val url = pigeonVar_list[0] as String?
      val mediaTracks = pigeonVar_list[1] as List<MediaTrack>?
      val metadata = pigeonVar_list[2] as MediaMetadata?
      val streamDuration = pigeonVar_list[3] as Long?
      return MediaInfo(url, mediaTracks, metadata, streamDuration)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      mediaTracks,
      metadata,
      streamDuration,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaQueueData (
  val items: List<MediaQueueItem>? = null,
  val startIndex: Long? = null,
  val queueType: MediaQueueType? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaQueueData {
      val items = pigeonVar_list[0] as List<MediaQueueItem>?
      val startIndex = pigeonVar_list[1] as Long?
      val queueType = pigeonVar_list[2] as MediaQueueType?
      return MediaQueueData(items, startIndex, queueType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      items,
      startIndex,
      queueType,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaQueueItem (
  val mediaInfo: MediaInfo? = null,
  val activeTrackIds: List<Long>? = null,
  val autoPlay: Boolean? = null,
  val startTime: Double? = null,
  val customDataJson: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaQueueItem {
      val mediaInfo = pigeonVar_list[0] as MediaInfo?
      val activeTrackIds = pigeonVar_list[1] as List<Long>?
      val autoPlay = pigeonVar_list[2] as Boolean?
      val startTime = pigeonVar_list[3] as Double?
      val customDataJson = pigeonVar_list[4] as String?
      return MediaQueueItem(mediaInfo, activeTrackIds, autoPlay, startTime, customDataJson)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      mediaInfo,
      activeTrackIds,
      autoPlay,
      startTime,
      customDataJson,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaTrack (
  val trackId: Long,
  val type: MediaTrackType,
  val contentId: String? = null,
  val subtype: MediaTrackSubtype? = null,
  val name: String? = null,
  val language: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaTrack {
      val trackId = pigeonVar_list[0] as Long
      val type = pigeonVar_list[1] as MediaTrackType
      val contentId = pigeonVar_list[2] as String?
      val subtype = pigeonVar_list[3] as MediaTrackSubtype?
      val name = pigeonVar_list[4] as String?
      val language = pigeonVar_list[5] as String?
      return MediaTrack(trackId, type, contentId, subtype, name, language)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      trackId,
      type,
      contentId,
      subtype,
      name,
      language,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaMetadata (
  val mediaType: MediaType,
  val title: String? = null,
  val seriesTitle: String? = null,
  val seasonNumber: Long? = null,
  val episodeNumber: Long? = null,
  val poster: MediaMetadataImage? = null,
  val backdrop: MediaMetadataImage? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaMetadata {
      val mediaType = pigeonVar_list[0] as MediaType
      val title = pigeonVar_list[1] as String?
      val seriesTitle = pigeonVar_list[2] as String?
      val seasonNumber = pigeonVar_list[3] as Long?
      val episodeNumber = pigeonVar_list[4] as Long?
      val poster = pigeonVar_list[5] as MediaMetadataImage?
      val backdrop = pigeonVar_list[6] as MediaMetadataImage?
      return MediaMetadata(mediaType, title, seriesTitle, seasonNumber, episodeNumber, poster, backdrop)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      mediaType,
      title,
      seriesTitle,
      seasonNumber,
      episodeNumber,
      poster,
      backdrop,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaMetadataImage (
  val url: String,
  val width: Long,
  val height: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaMetadataImage {
      val url = pigeonVar_list[0] as String
      val width = pigeonVar_list[1] as Long
      val height = pigeonVar_list[2] as Long
      return MediaMetadataImage(url, width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      width,
      height,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaSeekOptions (
  val position: Long,
  val resumeState: ResumeState
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaSeekOptions {
      val position = pigeonVar_list[0] as Long
      val resumeState = pigeonVar_list[1] as ResumeState
      return MediaSeekOptions(position, resumeState)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      position,
      resumeState,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaStatus (
  val playerState: PlayerState,
  val idleReason: IdleReason,
  val streamPosition: Long,
  val playbackRate: Double,
  val currentItemIndex: Long? = null,
  val activeTrackIds: List<Long>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaStatus {
      val playerState = pigeonVar_list[0] as PlayerState
      val idleReason = pigeonVar_list[1] as IdleReason
      val streamPosition = pigeonVar_list[2] as Long
      val playbackRate = pigeonVar_list[3] as Double
      val currentItemIndex = pigeonVar_list[4] as Long?
      val activeTrackIds = pigeonVar_list[5] as List<Long>?
      return MediaStatus(playerState, idleReason, streamPosition, playbackRate, currentItemIndex, activeTrackIds)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      playerState,
      idleReason,
      streamPosition,
      playbackRate,
      currentItemIndex,
      activeTrackIds,
    )
  }
}
private open class CastApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RoutesScanningMode.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          MediaQueueType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          MediaTrackType.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          MediaTrackSubtype.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          MediaType.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ResumeState.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          IdleReason.ofRaw(it.toInt())
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlayerState.ofRaw(it.toInt())
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaRoute.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaLoadRequestData.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaInfo.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaQueueData.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaQueueItem.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaTrack.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaMetadata.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaMetadataImage.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaSeekOptions.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaStatus.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is RoutesScanningMode -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is MediaQueueType -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is MediaTrackType -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is MediaTrackSubtype -> {
        stream.write(132)
        writeValue(stream, value.raw)
      }
      is MediaType -> {
        stream.write(133)
        writeValue(stream, value.raw)
      }
      is ResumeState -> {
        stream.write(134)
        writeValue(stream, value.raw)
      }
      is IdleReason -> {
        stream.write(135)
        writeValue(stream, value.raw)
      }
      is PlayerState -> {
        stream.write(136)
        writeValue(stream, value.raw)
      }
      is MediaRoute -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is MediaLoadRequestData -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is MediaInfo -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is MediaQueueData -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is MediaQueueItem -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is MediaTrack -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is MediaMetadata -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is MediaMetadataImage -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is MediaSeekOptions -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is MediaStatus -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CastApi {
  fun init(receiverAppId: String)
  fun registerRoutesListener(mode: RoutesScanningMode)
  fun unregisterRoutesListener(mode: RoutesScanningMode)
  fun selectRoute(id: String?)
  fun load(loadRequestData: MediaLoadRequestData)
  fun setActiveMediaTracks(trackIds: List<Long>)
  fun play()
  fun pause()
  fun seek(options: MediaSeekOptions)
  fun queueNext()
  fun queuePrev()
  fun setPlaybackRate(playbackRate: Double)
  fun sendMessage(namespace: String, message: String, callback: (Result<Unit>) -> Unit)
  fun stop()

  companion object {
    /** The codec used by CastApi. */
    val codec: MessageCodec<Any?> by lazy {
      CastApiPigeonCodec()
    }
    /** Sets up an instance of `CastApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CastApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.init$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val receiverAppIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.init(receiverAppIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.registerRoutesListener$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modeArg = args[0] as RoutesScanningMode
            val wrapped: List<Any?> = try {
              api.registerRoutesListener(modeArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.unregisterRoutesListener$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modeArg = args[0] as RoutesScanningMode
            val wrapped: List<Any?> = try {
              api.unregisterRoutesListener(modeArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.selectRoute$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String?
            val wrapped: List<Any?> = try {
              api.selectRoute(idArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.load$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val loadRequestDataArg = args[0] as MediaLoadRequestData
            val wrapped: List<Any?> = try {
              api.load(loadRequestDataArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.setActiveMediaTracks$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val trackIdsArg = args[0] as List<Long>
            val wrapped: List<Any?> = try {
              api.setActiveMediaTracks(trackIdsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.play$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.play()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.pause$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.pause()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.seek$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsArg = args[0] as MediaSeekOptions
            val wrapped: List<Any?> = try {
              api.seek(optionsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.queueNext$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.queueNext()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.queuePrev$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.queuePrev()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.setPlaybackRate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playbackRateArg = args[0] as Double
            val wrapped: List<Any?> = try {
              api.setPlaybackRate(playbackRateArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.sendMessage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val namespaceArg = args[0] as String
            val messageArg = args[1] as String
            api.sendMessage(namespaceArg, messageArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.cast_framework.CastApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stop()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class CastEventsApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by CastEventsApi. */
    val codec: MessageCodec<Any?> by lazy {
      CastApiPigeonCodec()
    }
  }
  fun onRoutesChanged(routesArg: List<MediaRoute>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.cast_framework.CastEventsApi.onRoutesChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(routesArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onStatusUpdated(statusArg: MediaStatus?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.cast_framework.CastEventsApi.onStatusUpdated$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(statusArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onMediaInfoUpdated(infoArg: MediaInfo?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.cast_framework.CastEventsApi.onMediaInfoUpdated$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(infoArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
