[package]
name = "zenith_flion"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre = "0.6.12"
flion = { git = "https://github.com/hasali19/flion" }
mpv-sys = { path = "../../../crates/mpv-sys" }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
windows-numerics = "0.1.1"
winit = "0.29.15"

[dependencies.windows]
version = "0.60"
features = ["Media", "UI_Composition"]

[build-dependencies]
embed-manifest = "1.3.1"
flion-build = { git = "https://github.com/hasali19/flion" }
windres = "0.2.2"
