[package]
name = "video_player_ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
gl = "0.14"
libloading = "0.7"

[dependencies.dart-sdk-sys]
path = "../../../crates/dart-sdk-sys"

[dependencies.flutter-plugin]
path = "../../../crates/flutter-plugin"

[dependencies.khronos-egl]
version = "4.1"
features = ["dynamic"]

[dependencies.mpv-sys]
path = "../../../crates/mpv-sys"

[dependencies.windows]
version = "0.48"
features = [
    "Foundation",
    "Media",
    "Win32_Foundation",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_System_WinRT",
    "Win32_UI_WindowsAndMessaging",
]
