name: video_player_ffi
description: A new Flutter plugin project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  video_player_platform_interface:
    path: ../video_player_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: video_player
    platforms:
      windows:
        pluginClass: VideoPlayerFfiPlugin
        dartPluginClass: VideoPlayerFfi
