targets:
  $default:
    builders:
      drift_dev:
        options:
          databases:
            zenith: lib/database/database.dart
          # To use ISO 8601 strings
          store_date_time_values_as_text: true
