[package]
name    = "zenith"
version = "0.0.0"
authors = ["Hasan Ali <git@hasali.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
color-eyre  = "0.5"
dotenv      = "0.15"
eyre        = "0.6"
env_logger  = "0.8"
futures     = "0.3"
itertools   = "0.10"
lazy_static = "1.4"
mime        = "0.3"
log         = "0.4"
notify      = "4.0"
regex       = "1.4"
serde_json  = "1.0"
serde_yaml  = "0.8"
time        = "0.2"
tokio-util  = "0.6"
url         = "2.2"

zenith_server = { path = "../zenith_server" }

[dependencies.reqwest]
version  = "0.11"
features = ["json"]

[dependencies.serde]
version  = "1.0"
features = ["derive"]

[dependencies.sqlx]
git              = "https://github.com/launchbadge/sqlx.git"
default-features = false
features         = ["macros", "runtime-tokio-native-tls", "sqlite"]

[dependencies.tokio]
version  = "1.1"
features = ["macros", "fs", "process"]
