[package]
name    = "zenith"
version = "0.0.0"
authors = ["Hasan Ali <git@hasali.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.4"
actix-web   = "3.3"
async-trait = "0.1"
color-eyre  = "0.5"
derive_more = "0.99"
eyre        = "0.6"
env_logger  = "0.8"
futures     = "0.3"
lazy_static = "1.4"
log         = "0.4"
regex       = "1.4"
serde       = "1.0"

[dependencies.sqlx]
version          = "0.4"
default-features = false
features         = ["runtime-actix-native-tls", "sqlite"]
