[package]
name    = "zenith"
version = "0.0.0"
authors = ["Hasan Ali <git@hasali.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.4"
actix-web   = "3.3"
async-trait = "0.1"
color-eyre  = "0.5"
derive_more = "0.99"
dotenv      = "0.15"
eyre        = "0.6"
env_logger  = "0.8"
futures     = "0.3"
itertools   = "0.9"
lazy_static = "1.4"
log         = "0.4"
notify      = "4.0"
pin-project = "1.0"
regex       = "1.4"
reqwest     = { version = "0.10", features = ["json"] }
serde       = "1.0"
serde_json  = "1.0"
serde_yaml  = "0.8"
time        = "0.2"
tokio       = { version = "0.2", features = ["fs", "process", "stream"] }
tokio-util  = "0.3"
url         = "2.2"

[dependencies.sqlx]
version          = "0.4"
default-features = false
features         = ["macros", "runtime-actix-native-tls", "sqlite"]
