[package]
name = "flutter-desktop-messenger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flutter-codec = { path = "../flutter-codec" }
flutter-windows-sys = { path = "../flutter-windows-sys" }
