[package]
name = "client-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy-regex = { workspace = true }
speq = { workspace = true, features = ["axum"] }
zenith = { path = "../zenith" }
