// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum RoutesScanningMode {
  none,
  passive,
  active,
}

enum MediaQueueType {
  generic,
  tvSeries,
  videoPlaylist,
  movie,
}

enum MediaTrackType {
  video,
  audio,
  text,
}

enum MediaTrackSubtype {
  subtitles,
}

enum MediaType {
  movie,
  tvShow,
  unknown,
}

enum ResumeState {
  pause,
  play,
  unchanged,
}

enum IdleReason {
  canceled,
  error,
  finished,
  interrupted,
  none,
}

enum PlayerState {
  idle,
  buffering,
  loading,
  paused,
  playing,
  unknown,
}

class MediaRoute {
  MediaRoute({
    required this.id,
    required this.name,
    this.description,
    required this.isSelected,
  });

  String id;

  String name;

  String? description;

  bool isSelected;

  List<Object?> _toList() {
    return <Object?>[
      id,
      name,
      description,
      isSelected,
    ];
  }

  Object encode() {
    return _toList();  }

  static MediaRoute decode(Object result) {
    result as List<Object?>;
    return MediaRoute(
      id: result[0]! as String,
      name: result[1]! as String,
      description: result[2] as String?,
      isSelected: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaRoute || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(name, other.name) && _deepEquals(description, other.description) && _deepEquals(isSelected, other.isSelected);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class MediaLoadRequestData {
  MediaLoadRequestData({
    this.mediaInfo,
    this.queueData,
    this.customDataJson,
  });

  MediaInfo? mediaInfo;

  MediaQueueData? queueData;

  String? customDataJson;

  List<Object?> _toList() {
    return <Object?>[
      mediaInfo,
      queueData,
      customDataJson,
    ];
  }

  Object encode() {
    return _toList();  }

  static MediaLoadRequestData decode(Object result) {
    result as List<Object?>;
    return MediaLoadRequestData(
      mediaInfo: result[0] as MediaInfo?,
      queueData: result[1] as MediaQueueData?,
      customDataJson: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaLoadRequestData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(mediaInfo, other.mediaInfo) && _deepEquals(queueData, other.queueData) && _deepEquals(customDataJson, other.customDataJson);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class MediaInfo {
  MediaInfo({
    this.url,
    this.mediaTracks,
    this.metadata,
    this.streamDuration,
    this.customDataJson,
  });

  String? url;

  List<MediaTrack>? mediaTracks;

  MediaMetadata? metadata;

  int? streamDuration;

  String? customDataJson;

  List<Object?> _toList() {
    return <Object?>[
      url,
      mediaTracks,
      metadata,
      streamDuration,
      customDataJson,
    ];
  }

  Object encode() {
    return _toList();  }

  static MediaInfo decode(Object result) {
    result as List<Object?>;
    return MediaInfo(
      url: result[0] as String?,
      mediaTracks: (result[1] as List<Object?>?)?.cast<MediaTrack>(),
      metadata: result[2] as MediaMetadata?,
      streamDuration: result[3] as int?,
      customDataJson: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(url, other.url) && _deepEquals(mediaTracks, other.mediaTracks) && _deepEquals(metadata, other.metadata) && _deepEquals(streamDuration, other.streamDuration) && _deepEquals(customDataJson, other.customDataJson);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class MediaQueueData {
  MediaQueueData({
    this.items,
    this.startIndex,
    this.queueType,
  });

  List<MediaQueueItem>? items;

  int? startIndex;

  MediaQueueType? queueType;

  List<Object?> _toList() {
    return <Object?>[
      items,
      startIndex,
      queueType,
    ];
  }

  Object encode() {
    return _toList();  }

  static MediaQueueData decode(Object result) {
    result as List<Object?>;
    return MediaQueueData(
      items: (result[0] as List<Object?>?)?.cast<MediaQueueItem>(),
      startIndex: result[1] as int?,
      queueType: result[2] as MediaQueueType?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaQueueData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(items, other.items) && _deepEquals(startIndex, other.startIndex) && _deepEquals(queueType, other.queueType);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class MediaQueueItem {
  MediaQueueItem({
    this.mediaInfo,
    this.activeTrackIds,
    this.autoPlay,
    this.startTime,
    this.customDataJson,
  });

  MediaInfo? mediaInfo;

  List<int>? activeTrackIds;

  bool? autoPlay;

  double? startTime;

  String? customDataJson;

  List<Object?> _toList() {
    return <Object?>[
      mediaInfo,
      activeTrackIds,
      autoPlay,
      startTime,
      customDataJson,
    ];
  }

  Object encode() {
    return _toList();  }

  static MediaQueueItem decode(Object result) {
    result as List<Object?>;
    return MediaQueueItem(
      mediaInfo: result[0] as MediaInfo?,
      activeTrackIds: (result[1] as List<Object?>?)?.cast<int>(),
      autoPlay: result[2] as bool?,
      startTime: result[3] as double?,
      customDataJson: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaQueueItem || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(mediaInfo, other.mediaInfo) && _deepEquals(activeTrackIds, other.activeTrackIds) && _deepEquals(autoPlay, other.autoPlay) && _deepEquals(startTime, other.startTime) && _deepEquals(customDataJson, other.customDataJson);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class MediaTrack {
  MediaTrack({
    required this.trackId,
    required this.type,
    this.contentId,
    this.subtype,
    this.name,
    this.language,
  });

  int trackId;

  MediaTrackType type;

  String? contentId;

  MediaTrackSubtype? subtype;

  String? name;

  String? language;

  List<Object?> _toList() {
    return <Object?>[
      trackId,
      type,
      contentId,
      subtype,
      name,
      language,
    ];
  }

  Object encode() {
    return _toList();  }

  static MediaTrack decode(Object result) {
    result as List<Object?>;
    return MediaTrack(
      trackId: result[0]! as int,
      type: result[1]! as MediaTrackType,
      contentId: result[2] as String?,
      subtype: result[3] as MediaTrackSubtype?,
      name: result[4] as String?,
      language: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaTrack || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(trackId, other.trackId) && _deepEquals(type, other.type) && _deepEquals(contentId, other.contentId) && _deepEquals(subtype, other.subtype) && _deepEquals(name, other.name) && _deepEquals(language, other.language);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class MediaMetadata {
  MediaMetadata({
    required this.mediaType,
    this.title,
    this.seriesTitle,
    this.seasonNumber,
    this.episodeNumber,
    this.poster,
    this.backdrop,
  });

  MediaType mediaType;

  String? title;

  String? seriesTitle;

  int? seasonNumber;

  int? episodeNumber;

  MediaMetadataImage? poster;

  MediaMetadataImage? backdrop;

  List<Object?> _toList() {
    return <Object?>[
      mediaType,
      title,
      seriesTitle,
      seasonNumber,
      episodeNumber,
      poster,
      backdrop,
    ];
  }

  Object encode() {
    return _toList();  }

  static MediaMetadata decode(Object result) {
    result as List<Object?>;
    return MediaMetadata(
      mediaType: result[0]! as MediaType,
      title: result[1] as String?,
      seriesTitle: result[2] as String?,
      seasonNumber: result[3] as int?,
      episodeNumber: result[4] as int?,
      poster: result[5] as MediaMetadataImage?,
      backdrop: result[6] as MediaMetadataImage?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaMetadata || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(mediaType, other.mediaType) && _deepEquals(title, other.title) && _deepEquals(seriesTitle, other.seriesTitle) && _deepEquals(seasonNumber, other.seasonNumber) && _deepEquals(episodeNumber, other.episodeNumber) && _deepEquals(poster, other.poster) && _deepEquals(backdrop, other.backdrop);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class MediaMetadataImage {
  MediaMetadataImage({
    required this.url,
    required this.width,
    required this.height,
  });

  String url;

  int width;

  int height;

  List<Object?> _toList() {
    return <Object?>[
      url,
      width,
      height,
    ];
  }

  Object encode() {
    return _toList();  }

  static MediaMetadataImage decode(Object result) {
    result as List<Object?>;
    return MediaMetadataImage(
      url: result[0]! as String,
      width: result[1]! as int,
      height: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaMetadataImage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(url, other.url) && _deepEquals(width, other.width) && _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class MediaSeekOptions {
  MediaSeekOptions({
    required this.position,
    required this.resumeState,
  });

  int position;

  ResumeState resumeState;

  List<Object?> _toList() {
    return <Object?>[
      position,
      resumeState,
    ];
  }

  Object encode() {
    return _toList();  }

  static MediaSeekOptions decode(Object result) {
    result as List<Object?>;
    return MediaSeekOptions(
      position: result[0]! as int,
      resumeState: result[1]! as ResumeState,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaSeekOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(position, other.position) && _deepEquals(resumeState, other.resumeState);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class MediaStatus {
  MediaStatus({
    required this.playerState,
    required this.idleReason,
    required this.streamPosition,
    required this.playbackRate,
    this.currentItemIndex,
    this.activeTrackIds,
  });

  PlayerState playerState;

  IdleReason idleReason;

  int streamPosition;

  double playbackRate;

  int? currentItemIndex;

  List<int>? activeTrackIds;

  List<Object?> _toList() {
    return <Object?>[
      playerState,
      idleReason,
      streamPosition,
      playbackRate,
      currentItemIndex,
      activeTrackIds,
    ];
  }

  Object encode() {
    return _toList();  }

  static MediaStatus decode(Object result) {
    result as List<Object?>;
    return MediaStatus(
      playerState: result[0]! as PlayerState,
      idleReason: result[1]! as IdleReason,
      streamPosition: result[2]! as int,
      playbackRate: result[3]! as double,
      currentItemIndex: result[4] as int?,
      activeTrackIds: (result[5] as List<Object?>?)?.cast<int>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaStatus || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(playerState, other.playerState) && _deepEquals(idleReason, other.idleReason) && _deepEquals(streamPosition, other.streamPosition) && _deepEquals(playbackRate, other.playbackRate) && _deepEquals(currentItemIndex, other.currentItemIndex) && _deepEquals(activeTrackIds, other.activeTrackIds);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is RoutesScanningMode) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is MediaQueueType) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is MediaTrackType) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is MediaTrackSubtype) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is MediaType) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is ResumeState) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    }    else if (value is IdleReason) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    }    else if (value is PlayerState) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    }    else if (value is MediaRoute) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is MediaLoadRequestData) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is MediaInfo) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is MediaQueueData) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is MediaQueueItem) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is MediaTrack) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    }    else if (value is MediaMetadata) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    }    else if (value is MediaMetadataImage) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    }    else if (value is MediaSeekOptions) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    }    else if (value is MediaStatus) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : RoutesScanningMode.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : MediaQueueType.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : MediaTrackType.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : MediaTrackSubtype.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : MediaType.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : ResumeState.values[value];
      case 135:
        final value = readValue(buffer) as int?;
        return value == null ? null : IdleReason.values[value];
      case 136:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlayerState.values[value];
      case 137:
        return MediaRoute.decode(readValue(buffer)!);
      case 138:
        return MediaLoadRequestData.decode(readValue(buffer)!);
      case 139:
        return MediaInfo.decode(readValue(buffer)!);
      case 140:
        return MediaQueueData.decode(readValue(buffer)!);
      case 141:
        return MediaQueueItem.decode(readValue(buffer)!);
      case 142:
        return MediaTrack.decode(readValue(buffer)!);
      case 143:
        return MediaMetadata.decode(readValue(buffer)!);
      case 144:
        return MediaMetadataImage.decode(readValue(buffer)!);
      case 145:
        return MediaSeekOptions.decode(readValue(buffer)!);
      case 146:
        return MediaStatus.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class CastApi {
  /// Constructor for [CastApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CastApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> init(String receiverAppId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.cast_framework.CastApi.init$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[receiverAppId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> registerRoutesListener(RoutesScanningMode mode) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.cast_framework.CastApi.registerRoutesListener$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[mode]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> unregisterRoutesListener(RoutesScanningMode mode) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.cast_framework.CastApi.unregisterRoutesListener$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[mode]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> selectRoute(String? id) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.cast_framework.CastApi.selectRoute$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[id]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> load(MediaLoadRequestData loadRequestData) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.cast_framework.CastApi.load$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[loadRequestData]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setActiveMediaTracks(List<int> trackIds) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.cast_framework.CastApi.setActiveMediaTracks$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[trackIds]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> play() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.cast_framework.CastApi.play$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> pause() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.cast_framework.CastApi.pause$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> seek(MediaSeekOptions options) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.cast_framework.CastApi.seek$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> queueNext() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.cast_framework.CastApi.queueNext$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> queuePrev() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.cast_framework.CastApi.queuePrev$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setPlaybackRate(double playbackRate) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.cast_framework.CastApi.setPlaybackRate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playbackRate]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> sendMessage(String namespace, String message) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.cast_framework.CastApi.sendMessage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[namespace, message]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> stop() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.cast_framework.CastApi.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

abstract class CastEventsApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onRoutesChanged(List<MediaRoute> routes);

  void onStatusUpdated(MediaStatus? status);

  void onMediaInfoUpdated(MediaInfo? info);

  static void setUp(CastEventsApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.cast_framework.CastEventsApi.onRoutesChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final List<MediaRoute> arg_routes = (args[0]! as List<Object?>).cast<MediaRoute>();
          try {
            api.onRoutesChanged(arg_routes);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.cast_framework.CastEventsApi.onStatusUpdated$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final MediaStatus? arg_status = args[0] as MediaStatus?;
          try {
            api.onStatusUpdated(arg_status);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.cast_framework.CastEventsApi.onMediaInfoUpdated$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final MediaInfo? arg_info = args[0] as MediaInfo?;
          try {
            api.onMediaInfoUpdated(arg_info);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
