[package]
name = "zenith"
version = "0.0.0"
authors = ["Hasan Ali <git@hasali.co.uk>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
bytes = "1.0"
color-eyre = "0.5"
eyre = "0.6"
futures = "0.3"
linkme = "0.2"
notify = "5.0.0-pre.13"
once_cell = "1.8"
regex = "1.5"
serde_json = "1.0"
serde_yaml = "0.8"
tokio-util = "0.6"
tracing = "0.1"
walkdir = "2.3"

axum-codegen = { path = "../axum-codegen" }
axum-files = { path = "../axum-files" }
migrations = { path = "../migrations" }
tmdb = { path = "../tmdb" }

[dependencies.axum]
git = "https://github.com/tokio-rs/axum"
rev = "decdd4c"
features = ["multipart"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.sqlx]
version = "0.5"
default-features = false
features = ["macros", "runtime-tokio-rustls", "sqlite"]

[dependencies.time]
version = "0.3"
features = ["parsing"]

[dependencies.tokio]
version = "1.10"
features = ["macros", "fs", "io-util", "process"]

[dependencies.tokio-stream]
version = "0.1"
features = ["sync"]

[dependencies.tower-http]
version = "0.1"
features = ["set-header", "trace"]

[dependencies.tracing-subscriber]
version = "0.3"
features = ["env-filter"]

[dependencies.uuid]
version = "0.8"
features = ["v4"]
