[package]
name = "zenith"
version = "0.0.0"
authors = ["Hasan Ali <git@hasali.co.uk>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.0-beta.8"
actix-multipart = "0.4.0-beta.7"
actix-web = "4.0.0-beta.10"
async-trait = "0.1"
bytes = "1.0"
color-eyre = "0.5"
eyre = "0.6"
futures = "0.3"
mime = "0.3"
once_cell = "1.8"
regex = "1.5"
serde_json = "1.0"
serde_yaml = "0.8"
tokio-util = "0.6"
tracing = "0.1"
tracing-actix-web = "0.4.0-beta.15"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "1.0"
walkdir = "2.3"

migrations = { path = "../migrations" }
tmdb = { path = "../tmdb" }

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.sqlx]
version = "0.5"
default-features = false
features = ["macros", "runtime-tokio-rustls", "sqlite"]

[dependencies.time]
version = "0.3"
features = ["parsing"]

[dependencies.tokio]
version = "1.10"
features = ["macros", "fs", "io-util", "process"]

[dependencies.tokio-stream]
version = "0.1"
features = ["sync"]

[dependencies.uuid]
version = "0.8"
features = ["v4"]
