name: Android

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/android.yml
      - android/**
    branches:
      - '**'
    tags-ignore:
      - '*/latest'

jobs:
  build_android:
    name: Build android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Build signed APK
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
          ANDROID_KEYSTORE_KEY_ALIAS: ${{ secrets.ANDROID_KEYSTORE_KEY_ALIAS }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEYSTORE_PATH: ../keystore.jks
        working-directory: android
        run: |
          echo $ANDROID_KEYSTORE | base64 -d > keystore.jks
          ./gradlew assembleRelease

      - uses: actions/upload-artifact@v3
        with:
          name: zenith-apk
          path: android/app/build/outputs/apk/release/app-release.apk
