name: Android Client

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: zenith_android

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build APK
        run: bash ./gradlew :app:assembleRelease

      - name: Sign APK
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
          ANDROID_KEYSTORE_KEY_ALIAS: ${{ secrets.ANDROID_KEYSTORE_KEY_ALIAS }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        run: |
          echo $ANDROID_KEYSTORE | base64 -d > keystore.jks
          $ANDROID_HOME/build-tools/30.0.3/zipalign -v -p 4 app/build/outputs/apk/release/app-release-unsigned.apk app-release-unsigned-aligned.apk
          $ANDROID_HOME/build-tools/30.0.3/apksigner sign --ks keystore.jks --ks-key-alias $ANDROID_KEYSTORE_KEY_ALIAS --ks-pass env:ANDROID_KEYSTORE_PASSWORD --out app-release.apk app-release-unsigned-aligned.apk

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: zenith_android_release
          path: zenith_android/app-release.apk
