name: CI

on:
  push:

jobs:
  build_server:
    name: Build server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache cargo output
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-rust-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-rust-

      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Build application
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --bin zenith
