name: Flutter

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/flutter.yml
      - client/flutter/**

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter build apk
        working-directory: client/flutter

      - uses: actions/upload-artifact@v2
        with:
          name: zenith-flutter-android
          path: client/flutter/build/app/outputs/flutter-apk/app-release.apk

  build_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter build web --web-renderer canvaskit
        working-directory: client/flutter

      - uses: actions/upload-artifact@v2
        with:
          name: zenith-flutter-web
          path: client/flutter/build/web

  deploy_web:
    runs-on: ubuntu-latest
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs:
      - build_web
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: zenith-flutter-web

      - run: echo "/* /index.html" > _redirects

      - uses: netlify/actions/cli@master
        with:
          args: deploy --dir=. --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter build windows
        working-directory: client/flutter

      - uses: actions/upload-artifact@v2
        with:
          name: zenith-flutter-windows
          path: client/flutter/build/windows/runner/Release
