name: video_player
description: A new Flutter plugin project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface:
    path: ../video_player_platform_interface
  video_player_web:
    path: ../video_player_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      web:
        default_package: video_player_web
